### PR TITLE
Laravel 8 support & travis ci improvements

### PR DESCRIPTION
**Pull request by veneliniliev**

### CODE REVIEW

**Comment by ssx** [comment]
Hi @veneliniliev,

Apologies for only seeing your PR now. I've already bumped the version, so if you want to merge in master and take that out, 'll get your travis changes merged in.

**Comment by veneliniliev** [comment]
@ssx merged with current master

**Comment by ssx** [comment]
Awesome!

I’ll have a look this weekend and get it all sorted. We can then use same
approach for the other packages too.

**Comment by ssx** [comment]
This has been superseded by changes from @clarkeash, thanks for the PR though!

**Pull request closed without merging**
