### PR TITLE
Custom validation messages with localization support

### PR DESCRIPTION
**Pull request by ThisIsPita**
This would allow custom validation messages with localization support. Messages would need to be added to lang/{language}/validation.php under 'country2' and 'country3' keys.

'country2' => 'Invalid ISO3166-A2 country code.',
'country3' => 'Invalid ISO3166-A3 country code.',

### CODE REVIEW

**Comment by bilfeldt** [comment]
This is a really nice update. But just note that this is sort of a breaking change, since people with this package installed might already have tests looking for the error messages hardcoded in the code.

**Comment by clarkeash** [comment]
Thats kinda why I've held off on merging this. I need to have a think about it.

**Comment by tylercd100** [comment]
We could get this to work by creating a Laravel Service Provider that publishes the lang files automatically? Let me know if this is a direction you'd like to take and if you need any help. Including translation files might be a good thing for all LVR packages going forward?

**Comment by ssx** [comment]
I think that may be a route we can take. Will have a think this week.

**Comment by ssx** [comment]
I still think this is a really good idea @ThisIsPita - do you want to merge in latest master and add a service provider to publish the lang files?

**Comment by ssx** [comment]
Closing due to no activity.

**Pull request closed without merging**
